version: "3.5"

services:

  backend:
    build:
      context: ./example-backend/.
      dockerfile: Dockerfile.golan
    image: backend:exercise-3.5-golan
    
    environment:
      - REQUEST_ORIGIN=http://localhost
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=password123
          
    container_name: backend

  frontend:
    build: ./example-frontend/.
    image: frontend:exercise-3.5
    environment:
      - API_URL=http://localhost/api
    container_name: frontend

  redis:
    image: redis

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password123
      PGDATA: ./database
    container_name: database_backend
    volumes:
      - database:/database

  proxy:
    image: nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
volumes:
  database:
