FROM golang:1.16.4-alpine3.13 as build-stage
WORKDIR /usr/app
COPY . .
# Build statically linked libraries
RUN env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o server

FROM scratch
COPY --from=build-stage /usr/app/server /
EXPOSE 8080
ENTRYPOINT [ "/server" ]
