version: "3.5"

services:
  backend:
    build: ./backend/.
    ports:
      - 1338:8000
    environment:
      - FRONT_URL=http://localhost:1337
      - REDIS=redis
      - REDIS_PORT=6379
      - DB_USERNAME=postgres
      - DB_PASSWORD=password123
      - DB_NAME=postgres
      - DB_HOST=db
  frontend:
    build: ./frontend/.
    ports:
      - 1337:5000
    environment:
      - API_URL=http://localhost:1338
  redis:
    image: redis

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password123
    container_name: database_backend
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database:

